// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDwoS8hG4TRtx8ItzGjmJipihB9YmjDu4',
    appId: '1:329296183038:web:933ea58d1ec12f8f79efaf',
    messagingSenderId: '329296183038',
    projectId: 'kilagbe-app',
    authDomain: 'kilagbe-app.firebaseapp.com',
    storageBucket: 'kilagbe-app.firebasestorage.app',
    measurementId: 'G-WY5Y75XCWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5tl_FPpk9Lu5kQ_K27oy7zzSXt8gC9r4',
    appId: '1:329296183038:android:abfbf92a1afe62b779efaf',
    messagingSenderId: '329296183038',
    projectId: 'kilagbe-app',
    storageBucket: 'kilagbe-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABNmh_g_EGQ7gCGXhkBMF6Sn5YE5U5WBQ',
    appId: '1:329296183038:ios:fe22a6fddd494c2f79efaf',
    messagingSenderId: '329296183038',
    projectId: 'kilagbe-app',
    storageBucket: 'kilagbe-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication23',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABNmh_g_EGQ7gCGXhkBMF6Sn5YE5U5WBQ',
    appId: '1:329296183038:ios:fe22a6fddd494c2f79efaf',
    messagingSenderId: '329296183038',
    projectId: 'kilagbe-app',
    storageBucket: 'kilagbe-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication23',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDwoS8hG4TRtx8ItzGjmJipihB9YmjDu4',
    appId: '1:329296183038:web:6ef444d8a349d03179efaf',
    messagingSenderId: '329296183038',
    projectId: 'kilagbe-app',
    authDomain: 'kilagbe-app.firebaseapp.com',
    storageBucket: 'kilagbe-app.firebasestorage.app',
    measurementId: 'G-62SH8VMQ3Q',
  );
}
